
```{bash}
#ssh -i ~/.ssh/id_rsa -L 33306:web.ghtorrent.org:3306 ghtorrent@web.ghtorrent.org
#ps axuf | grep ssh
#mysql -u ght -h 127.0.0.1 -P 33306 ghtorrent
```


```{r}
library("knitr")
library("ggplot2")
library(readr)
library("reshape")
library(RMySQL)
#library(sqldf)
library(optparse)
library(foreach)#
library(doMC)#

require(devtools)

```

* Создать базу с топ-50 организаций + их проекты и участники 
* Посмотреть библиотеки для  больших данных в р 
* Длина обработки реквестов и "важность" или вовлеченность участника 
* Подумать как можно выделять основных участников (core) проекта

```{r}
#попробовать переделать с dplyr
#my_db <- src_mysql("ghtorrent", host = '127.0.0.1', port = 33306, user = "ght", password = "")

library(optparse)
library(knitr)
#rm(list = ls(all = TRUE))

mysql.user   =  "ght"
mysql.passwd = ""
mysql.db     = "ghtorrent"
mysql.host   = "127.0.0.1"
mysql.port = 33306
paralll      = 4

library(RMySQL)

ghtor = dbConnect(dbDriver("MySQL"),
          user = mysql.user,
          password = mysql.passwd,
          dbname = mysql.db,
          host = mysql.host,
          port = mysql.port)

#dbClearResult(dbListResults(ghtor)[[1]])
dbListFields(ghtor,"projects")
dbListTables(ghtor)
```


Участники топ-10 организаций
```{r}
top_organizations = dbGetQuery(ghtor, "select org_id, COUNT(*) as total_m from organization_members group by org_id order by total_m DESC limit 50") %>% arrange(desc(total_m)) #топ 50 организаций по кол-ву участников 
#select id, login from users where id = '95143' 

top_10 = paste(c(top_organizations[1:10,1]), collapse = "','")

#кто эти топовые организации
#dbGetQuery(ghtor, paste0(c('select id,login from users where id in ', "('", top_10, "')"), collapse = ""))

members = paste0(c('select * from organization_members where org_id in ', "('", top_10, "')"), collapse = "")
members = dbGetQuery(ghtor, members) 

#write_csv(top_organizations, "~/emc_github_project/top_organizations.csv")
#write_csv(members, "~/emc_github_project/members.csv")
```


Чек по проектам 
```{r}
#достать проекты, где владельцы - топ орги
projects = paste0(c('select * from projects where owner_id in ', "('", top_10, "')"), collapse = "")
projects = dbGetQuery(ghtor, projects) 


project_commits = dbGetQuery(ghtor, paste0(c('select * from project_commits where project_id in ', "('", top_10, "')"), collapse = "")) 

repo_labels = dbGetQuery(ghtor, "select * from project_languages where project_id = '2067195'") 


pull_requests = dbGetQuery(ghtor, paste0(c('select * from pull_requests where base_repo_id in ', "('", top_10, "')"), collapse = "")) 


commits = dbGetQuery(ghtor, paste0(c('select * from commits where project_id in ', "('", top_10, "')"), collapse = ""))  #не у всех проектов есть коммиты


```


По юзерам
```{r}
users_new = paste(c(members$user_id[1:100]), collapse = "','")

u_commits = dbGetQuery(ghtor, paste0(c('select * from commits where committer_id in ', "('", users_new, "')"), collapse = ""))
```


